/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prefoodorderingapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static prefoodorderingapp.Menu.buildTableModel;

/**
 *
 * @author Vinu
 */
public class Chashier extends javax.swing.JFrame {
    
    private Connection connect = Connections.getConnection();
    private Statement statement = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet resultSet = null;
    
    ResultSet rs = null;
    
    float price = 0;
    float ttl = 0;
    String currentOrder = "INVALID";
    
    public void fillOrdersTable(String ord) throws SQLException{
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = connect;
            Statement stmt = con.createStatement();  
            ResultSet rs = stmt.executeQuery("SELECT * FROM orders WHERE UserID='"+ ord +"' AND NOT Status = 1");
            
            
            tabelorder.setModel(buildTableModel(rs));
            
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,ex );
        }
    }
    
    
    public void fillProductname(String pname) throws SQLException{
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = connect;
            Statement stmt = con.createStatement();  
            ResultSet rs = stmt.executeQuery("select * from proudcts where ProductName='"+ pname +"'");
            
            
            tabelorder.setModel(buildTableModel(rs));
            
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,ex );
        }
    }
    
  
    
    public static DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

    ResultSetMetaData metaData = rs.getMetaData();

    // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = metaData.getColumnCount();
    for (int column = 1; column <= columnCount; column++) {
        columnNames.add(metaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }

    return new DefaultTableModel(data, columnNames);

}

    /** Creates new form Chashier */
    public Chashier() throws SQLException {
        initComponents();
        
        //fillOrdersTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        btnclearo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblpname = new javax.swing.JLabel();
        txtordersrch = new javax.swing.JTextField();
        btnordersrch = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbloid = new javax.swing.JLabel();
        lbluoname = new javax.swing.JLabel();
        lblopid = new javax.swing.JLabel();
        lbloqon = new javax.swing.JLabel();
        lblop = new javax.swing.JLabel();
        lbltot = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelorder = new javax.swing.JTable();
        btnpay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 198, 187));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(134, 226, 213));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setBackground(new java.awt.Color(162, 222, 208));
        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 48)); // NOI18N
        jLabel3.setText("CHASHIER PAGE....");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(632, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-10, 0, 1340, 100);

        btncancel.setBackground(new java.awt.Color(246, 36, 89));
        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setText("CANCEL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel);
        btncancel.setBounds(870, 700, 130, 50);

        btnclearo.setBackground(new java.awt.Color(78, 205, 196));
        btnclearo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnclearo.setText("CLEAR");
        btnclearo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearoActionPerformed(evt);
            }
        });
        jPanel1.add(btnclearo);
        btnclearo.setBounds(600, 120, 100, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Total:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 460, 70, 70);

        lblpname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblpname.setText("------");
        lblpname.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblpnamePropertyChange(evt);
            }
        });
        jPanel1.add(lblpname);
        lblpname.setBounds(170, 350, 290, 40);

        txtordersrch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtordersrch);
        txtordersrch.setBounds(100, 120, 370, 40);

        btnordersrch.setBackground(new java.awt.Color(78, 205, 196));
        btnordersrch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnordersrch.setText("SEARCH");
        btnordersrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordersrchActionPerformed(evt);
            }
        });
        jPanel1.add(btnordersrch);
        btnordersrch.setBounds(480, 120, 110, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Name:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 100, 80, 70);

        j.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        j.setText("Name:");
        jPanel1.add(j);
        j.setBounds(30, 240, 130, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Order ID:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 200, 100, 50);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Product ID:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 270, 100, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Price:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 380, 60, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Product Name:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(30, 340, 120, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Quantity:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 300, 90, 50);

        lbloid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbloid.setText("------");
        lbloid.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbloidPropertyChange(evt);
            }
        });
        jPanel1.add(lbloid);
        lbloid.setBounds(130, 210, 290, 40);

        lbluoname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbluoname.setText("------");
        jPanel1.add(lbluoname);
        lbluoname.setBounds(120, 240, 290, 40);

        lblopid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblopid.setText("------");
        jPanel1.add(lblopid);
        lblopid.setBounds(130, 270, 290, 40);

        lbloqon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbloqon.setText("------");
        jPanel1.add(lbloqon);
        lbloqon.setBounds(120, 310, 290, 40);

        lblop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblop.setText("------");
        jPanel1.add(lblop);
        lblop.setBounds(90, 380, 290, 40);

        lbltot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltot.setText("------");
        jPanel1.add(lbltot);
        lbltot.setBounds(110, 480, 290, 40);

        tabelorder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabelorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "UserID", "ProductID", "Quantity", "Paying status"
            }
        ));
        tabelorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelorderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelorder);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(310, 190, 640, 480);

        btnpay.setBackground(new java.awt.Color(78, 205, 196));
        btnpay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnpay.setText("PAY");
        btnpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpayActionPerformed(evt);
            }
        });
        jPanel1.add(btnpay);
        btnpay.setBounds(30, 520, 220, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnclearoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearoActionPerformed
        // TODO add your handling code here:
        txtordersrch.setText(null);
    }//GEN-LAST:event_btnclearoActionPerformed

    private void btnordersrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordersrchActionPerformed
        // TODO add your handling code here:
        String ord = txtordersrch.getText().toString();
        
       try {
            fillOrdersTable(ord);
        } catch (SQLException ex) {
            Logger.getLogger(Ordering.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnordersrchActionPerformed

    private void tabelorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelorderMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) tabelorder.getModel();
        int selectedRowIndex = tabelorder.getSelectedRow();
        
        lbloid.setText(tblModel.getValueAt(selectedRowIndex,0).toString());
        lbluoname.setText(tblModel.getValueAt(selectedRowIndex,1).toString());
        lblopid.setText(tblModel.getValueAt(selectedRowIndex,2).toString());
        lbloqon.setText(tblModel.getValueAt(selectedRowIndex,3).toString());
        
        currentOrder = tblModel.getValueAt(selectedRowIndex,0).toString();
        
        System.out.print(currentOrder);
        
        try {
                Connection con = Connections.getConnection();
                String MyQuery = "SELECT * FROM proudcts WHERE ProductID = "+tblModel.getValueAt(selectedRowIndex,2).toString()+";";
                
                
                PreparedStatement pres = con.prepareStatement(MyQuery);
                ResultSet res =  pres.executeQuery();
                
                
                while(res.next()){
                    lblpname.setText(res.getString("ProductName"));
                    lblop.setText("LKR " + res.getString("Price")+"/=");
                    price = Float.parseFloat(res.getString("Price"));
                    ttl = price * Float.parseFloat(tblModel.getValueAt(selectedRowIndex,3).toString());
                }
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Ordering.class.getName()).log(Level.SEVERE, null, ex);
            }
        lbltot.setText("LKR " + Float.toString(ttl)+"/=");
        
        
    }//GEN-LAST:event_tabelorderMouseClicked

    private void btnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = Connections.getConnection();
            String MyQuery = "UPDATE orders SET Status = 1 WHERE id = " + currentOrder +";";
            PreparedStatement pres = con.prepareStatement(MyQuery);
            pres.execute();
            JOptionPane.showMessageDialog(this, "Payment Completed!");

        } catch (Exception ex) {
            ///Logger.getLogger(Maintance.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong..!");
            JOptionPane.showMessageDialog(this,ex );
        }
        //
        DefaultTableModel model = (DefaultTableModel) tabelorder.getModel();
        model.setRowCount(0);
        
    }//GEN-LAST:event_btnpayActionPerformed

    private void lbloidPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbloidPropertyChange
        // TODO add your handling code here:
       //String pname = lblpname.getText().toString();
       /*
        
       */
        
    }//GEN-LAST:event_lbloidPropertyChange

    private void lblpnamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblpnamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblpnamePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Chashier().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Chashier.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnclearo;
    private javax.swing.JButton btnordersrch;
    private javax.swing.JButton btnpay;
    private javax.swing.JLabel j;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbloid;
    private javax.swing.JLabel lblop;
    private javax.swing.JLabel lblopid;
    private javax.swing.JLabel lbloqon;
    private javax.swing.JLabel lblpname;
    private javax.swing.JLabel lbltot;
    private javax.swing.JLabel lbluoname;
    private javax.swing.JTable tabelorder;
    private javax.swing.JTextField txtordersrch;
    // End of variables declaration//GEN-END:variables

}
