/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prefoodorderingapp;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinu
 */
public class LoginPg extends javax.swing.JFrame {
    
    public String uName = "INVALID";
    public String uType = "INVALID";
    /**
     * Creates new form LoginPg
     */
    public LoginPg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btncancel = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        txtpw = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblreg = new javax.swing.JLabel();
        combotype = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btncancel.setBackground(new java.awt.Color(246, 36, 89));
        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setText("CANCEL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel);
        btncancel.setBounds(380, 490, 130, 50);

        btnlogin.setBackground(new java.awt.Color(78, 205, 196));
        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin);
        btnlogin.setBounds(210, 490, 130, 50);

        txtpw.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtpw);
        txtpw.setBounds(180, 380, 370, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Password:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 360, 110, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("User Type:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 230, 130, 70);

        txtusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtusername);
        txtusername.setBounds(180, 310, 370, 40);

        jLabel3.setBackground(new java.awt.Color(162, 222, 208));
        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        jLabel3.setText("WELCOME TO OUR LOGIN PAGE ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 110, 580, 70);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("User Name:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 290, 130, 70);

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 48)); // NOI18N
        jLabel2.setText("FAST FOODS...");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, -20, 530, 130);

        lblreg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblreg.setText("Click Here To Create New Account.....");
        lblreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregMouseClicked(evt);
            }
        });
        jPanel1.add(lblreg);
        lblreg.setBounds(140, 640, 420, 60);

        combotype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        combotype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Customer" }));
        jPanel1.add(combotype);
        combotype.setBounds(180, 240, 370, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prefoodorderingapp/aaa1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1260, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1261, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregMouseClicked
        // TODO add your handling code here:
        
        Registration rg = new Registration();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lblregMouseClicked

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        operations opp = new operations();
        
        try{
            String usertypest = combotype.getSelectedItem().toString();
            String usernamest = txtusername.getText();
            String passwordst = txtpw.getText();
            
            if(opp.isLogin(usertypest, usernamest, passwordst, this)){
                
                uName = txtusername.getText();
                uType = combotype.getSelectedItem().toString();
                
                loginsession.UserName = uName;
                
                
                new Home().setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this,"something went wrong.try again...", "Error",1);     
            }
           
       }catch(Exception ex){
           JOptionPane.showMessageDialog(this,"Something went wrong...", "Error",1);
       }
              
        
    }//GEN-LAST:event_btnloginActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnlogin;
    private javax.swing.JComboBox<String> combotype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblreg;
    private javax.swing.JPasswordField txtpw;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
