/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prefoodorderingapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinu
 */
public class Ordering extends javax.swing.JFrame {
    
     
    private Connection connect = Connections.getConnection();
    private Statement statement = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet resultSet = null;
    
    public List<OrderObj> Orders = new ArrayList<OrderObj>();
    
    public String pID = "INVALID";
    
    public String uID = loginsession.UserName;
    
    ResultSet rs = null;
    
    float ttl = 0;
    
    public void fillProductListTable(String cat) throws SQLException{
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = connect;
            Statement stmt = con.createStatement();  
            ResultSet rs = stmt.executeQuery("select * from proudcts where Category='"+ cat +"'");
            
            
            tableproductlist.setModel(buildTableModel(rs));
            
            
        } catch (ClassNotFoundException ex) {
            //
        }
    }
    
    public static DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

    ResultSetMetaData metaData = rs.getMetaData();

    // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = metaData.getColumnCount();
    for (int column = 1; column <= columnCount; column++) {
        columnNames.add(metaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }

    return new DefaultTableModel(data, columnNames);

}

    /**
     * Creates new form Ordering
     */
    public Ordering() {
        initComponents();
        lbluid1.setText(uID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableproductlist = new javax.swing.JTable();
        btnpsrch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        lbluid = new javax.swing.JLabel();
        btnremove = new javax.swing.JButton();
        btnorder = new javax.swing.JButton();
        btnaddcart = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtqon = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        comboptype = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        lbluid1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BTNCLEAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(101, 198, 187));
        jPanel5.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(134, 226, 213));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel5.setBackground(new java.awt.Color(162, 222, 208));
        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 48)); // NOI18N
        jLabel5.setText("ORDERING PAGE....");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(612, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(-10, 0, 1320, 100);

        btncancel.setBackground(new java.awt.Color(246, 36, 89));
        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setText("CANCEL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel5.add(btncancel);
        btncancel.setBounds(1120, 720, 130, 50);

        tableproductlist.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableproductlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price  (Rs.)", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableproductlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableproductlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableproductlist);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(20, 350, 630, 310);

        btnpsrch.setBackground(new java.awt.Color(78, 205, 196));
        btnpsrch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnpsrch.setText("SEARCH");
        btnpsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpsrchActionPerformed(evt);
            }
        });
        jPanel5.add(btnpsrch);
        btnpsrch.setBounds(320, 260, 110, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Cart");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(990, 100, 40, 50);

        lblprice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblprice.setText("-----------");
        jPanel5.add(lblprice);
        lblprice.setBounds(110, 680, 170, 22);

        lbluid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbluid.setText("-------");
        jPanel5.add(lbluid);
        lbluid.setBounds(1010, 540, 160, 22);

        btnremove.setBackground(new java.awt.Color(78, 205, 196));
        btnremove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnremove.setText("Remove the Cart");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });
        jPanel5.add(btnremove);
        btnremove.setBounds(840, 580, 200, 50);

        btnorder.setBackground(new java.awt.Color(78, 205, 196));
        btnorder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnorder.setText("Order Now");
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });
        jPanel5.add(btnorder);
        btnorder.setBounds(1070, 580, 130, 50);

        btnaddcart.setBackground(new java.awt.Color(78, 205, 196));
        btnaddcart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnaddcart.setText("ADD TO CART");
        btnaddcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddcartActionPerformed(evt);
            }
        });
        jPanel5.add(btnaddcart);
        btnaddcart.setBounds(460, 680, 170, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Price:");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(30, 670, 60, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Total:");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(910, 520, 100, 60);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Products Category:");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(10, 200, 150, 60);

        txtqon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtqon.setText("0");
        jPanel5.add(txtqon);
        txtqon.setBounds(120, 730, 100, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Quantity:");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(30, 720, 90, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Products:");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(20, 300, 120, 50);

        comboptype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboptype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice & Curry", "Drinks", "Shorties" }));
        jPanel5.add(comboptype);
        comboptype.setBounds(180, 220, 360, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("User Name :");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(20, 140, 110, 60);

        lbluid1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbluid1.setText("-------");
        jPanel5.add(lbluid1);
        lbluid1.setBounds(130, 160, 350, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextArea1.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(790, 140, 450, 390);

        BTNCLEAR.setBackground(new java.awt.Color(78, 205, 196));
        BTNCLEAR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTNCLEAR.setText("CLEAR");
        BTNCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCLEARActionPerformed(evt);
            }
        });
        jPanel5.add(BTNCLEAR);
        BTNCLEAR.setBounds(450, 260, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1281, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnpsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpsrchActionPerformed
        
        String cat = comboptype.getSelectedItem().toString();
        
        try {
            fillProductListTable(cat);
        } catch (SQLException ex) {
            Logger.getLogger(Ordering.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_btnpsrchActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        // TODO add your handling code here:
        for (OrderObj obj : Orders){
            try{
            Connection con = Connections.getConnection();
            String MyQuery = "INSERT INTO Orders (UserID,ProductID,Qty) VALUES (?,?,?)";
            PreparedStatement pres = con.prepareStatement(MyQuery);
            //ResultSet res =  pres.executeUpdate();
            pres.setString(1, obj.UserID);
            pres.setString(2, obj.ProductID);
            pres.setInt(3, obj.Qty);
            pres.execute();
            
            
            
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error");
            JOptionPane.showMessageDialog(this,ex );
            
        }
        }
        JOptionPane.showMessageDialog(this, "Your Order is Successful");
    }//GEN-LAST:event_btnorderActionPerformed

    private void btnaddcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddcartActionPerformed
        
        OrderObj order  = new OrderObj();
        order.OrderObj(uID,pID,Integer.parseInt(txtqon.getText().toString()));
        Orders.add(order);
        String CartList = "";
        ttl = 0;
        for (OrderObj obj : Orders){
            float price = 0;
            try {
                CartList += "\n Product ID: "  + obj.ProductID + "\n User: "  + obj.UserID + "\n Quantity: "  + obj.Qty + "\n";
                
                
                Connection con = Connections.getConnection();
                String MyQuery = "SELECT * FROM proudcts WHERE ProductID = "+obj.ProductID+";";
                
                
                PreparedStatement pres = con.prepareStatement(MyQuery);
                ResultSet res =  pres.executeQuery();
                
                
                while(res.next()){
                    price = Float.parseFloat(res.getString("Price"));
                }
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Ordering.class.getName()).log(Level.SEVERE, null, ex);
            }
            ttl = ttl + (price * obj.Qty);
        }
        
        jTextArea1.setText(CartList);
        lbluid.setText(Float.toString(ttl));
        
    }//GEN-LAST:event_btnaddcartActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        // TODO add your handling code here:
        Orders.clear();
        jTextArea1.setText("");
        ttl = 0;
        lbluid.setText("----");
    }//GEN-LAST:event_btnremoveActionPerformed

    private void tableproductlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableproductlistMouseClicked
        DefaultTableModel tblModel = (DefaultTableModel) tableproductlist.getModel();
        int selectedRowIndex = tableproductlist.getSelectedRow();
        
        lblprice.setText(tblModel.getValueAt(selectedRowIndex,2).toString());
        pID = tblModel.getValueAt(selectedRowIndex,0).toString();
        
        
    }//GEN-LAST:event_tableproductlistMouseClicked

    private void BTNCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCLEARActionPerformed
        // TODO add your handling code here:
        comboptype.setSelectedItem(null);
    }//GEN-LAST:event_BTNCLEARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordering().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCLEAR;
    private javax.swing.JButton btnaddcart;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnorder;
    private javax.swing.JButton btnpsrch;
    private javax.swing.JButton btnremove;
    private javax.swing.JComboBox<String> comboptype;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lbluid;
    private javax.swing.JLabel lbluid1;
    private javax.swing.JTable tableproductlist;
    private javax.swing.JTextField txtqon;
    // End of variables declaration//GEN-END:variables
}
