/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prefoodorderingapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import static prefoodorderingapp.CustomerDetails.buildTableModel;

/**
 *
 * @author Vinu
 */
public class ProductMaintance extends javax.swing.JFrame {
    
    
    private Connection connect = Connections.getConnection();
    private Statement statement = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet resultSet = null;
    
    ResultSet rs = null;
    
    public void fillTable() throws SQLException{
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = connect;
            Statement stmt = con.createStatement();  
            ResultSet rs = stmt.executeQuery("select * from proudcts");
            
            
            producttable.setModel(buildTableModel(rs));
            
            
        } catch (ClassNotFoundException ex) {
            //
        }
    }
    
    public void fillproducttabelsrch(String Pids) throws SQLException {
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = connect;
            Statement stmt = con.createStatement();  
            ResultSet rs = stmt.executeQuery("select * from proudcts where ProductID='"+ Pids +"'");
            if ("Customer".equals(loginsession.UserType)){
                 rs = stmt.executeQuery("select * from proudcts where ProductID='"+ Pids +"'");
             } else {
                 rs = stmt.executeQuery("select * from proudcts where ProductID='"+ Pids +"'");
             }
            
            producttable.setModel(buildTableModel(rs));
            
            
        
        }catch(ClassNotFoundException ex){
              JOptionPane.showMessageDialog(this,ex );
        }
            
            
    }
    
    public static DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

    ResultSetMetaData metaData = rs.getMetaData();

    // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = metaData.getColumnCount();
    for (int column = 1; column <= columnCount; column++) {
        columnNames.add(metaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }

    return new DefaultTableModel(data, columnNames);

}
    
    

    /**
     * Creates new form ProductMaintance
     */
    public ProductMaintance() throws SQLException {
        initComponents();
        
        fillTable();
         //updatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        producttable = new javax.swing.JTable();
        txtpidsrch = new javax.swing.JTextField();
        btnsrch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboptype = new javax.swing.JComboBox<>();
        txtp = new javax.swing.JTextField();
        txtpname = new javax.swing.JTextField();
        txtpid = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btncansel = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();
        btnclr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(101, 198, 187));

        jPanel1.setBackground(new java.awt.Color(232, 236, 241));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(25, 118, 210));

        jLabel3.setBackground(new java.awt.Color(25, 118, 210));
        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Maintance");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(576, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-10, 0, 1300, 100);

        producttable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        producttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price  (Rs.)", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        producttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                producttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(producttable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(490, 210, 740, 480);
        jPanel1.add(txtpidsrch);
        txtpidsrch.setBounds(160, 120, 820, 40);

        btnsrch.setBackground(new java.awt.Color(25, 118, 210));
        btnsrch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsrch.setForeground(new java.awt.Color(255, 255, 255));
        btnsrch.setText("SEARCH");
        btnsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsrch);
        btnsrch.setBounds(990, 120, 120, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Product ID:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 120, 130, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Product ID:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 190, 130, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Product Name:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 280, 180, 50);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Price:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 370, 80, 50);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Category:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 460, 120, 50);

        comboptype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboptype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice & Curry", "Drinks", "Shorties" }));
        jPanel1.add(comboptype);
        comboptype.setBounds(30, 510, 430, 40);

        txtp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtp);
        txtp.setBounds(30, 420, 430, 40);

        txtpname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtpname);
        txtpname.setBounds(30, 320, 430, 40);

        txtpid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtpid);
        txtpid.setBounds(30, 240, 430, 40);

        btnsave.setBackground(new java.awt.Color(25, 118, 210));
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("ADD");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave);
        btnsave.setBounds(70, 580, 130, 50);

        jButton3.setBackground(new java.awt.Color(25, 118, 210));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(70, 650, 130, 50);

        btncansel.setBackground(new java.awt.Color(246, 36, 89));
        btncansel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncansel.setForeground(new java.awt.Color(255, 255, 255));
        btncansel.setText("CANCEL");
        btncansel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncanselActionPerformed(evt);
            }
        });
        jPanel1.add(btncansel);
        btncansel.setBounds(1100, 700, 130, 50);

        btnupdate.setBackground(new java.awt.Color(25, 118, 210));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate);
        btnupdate.setBounds(250, 580, 130, 50);

        btnremove.setBackground(new java.awt.Color(25, 118, 210));
        btnremove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnremove.setForeground(new java.awt.Color(255, 255, 255));
        btnremove.setText("REMOVE");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnremove);
        btnremove.setBounds(250, 650, 130, 50);

        btnclr.setBackground(new java.awt.Color(25, 118, 210));
        btnclr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnclr.setForeground(new java.awt.Color(255, 255, 255));
        btnclr.setText("CLEAR");
        btnclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclrActionPerformed(evt);
            }
        });
        jPanel1.add(btnclr);
        btnclr.setBounds(1120, 120, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrchActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = Connections.getConnection();
            String MyQuery = "SELECT * FROM proudcts WHERE ProductID='" + txtpidsrch.getText()+"'";
            PreparedStatement pres = con.prepareStatement(MyQuery);
            pres.execute();
            
        } catch (SQLException ex) {
            Logger.getLogger(ProductMaintance.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         String Pids = txtpidsrch.getText().toString();
        
       try {
            fillproducttabelsrch(Pids);
        } catch (Exception ex) {
            Logger.getLogger(Ordering.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsrchActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

        try{                                        
            // TODO add your handling code here:
            if (!txtpid.getText().isEmpty() || !txtpname.getText().isEmpty() || !txtp.getText().isEmpty()){
                try{
                Connection con = Connections.getConnection();
                String MyQuery = "INSERT INTO proudcts (ProductID,ProductName,Price,Category) VALUES (?,?,?,?)";
                PreparedStatement pres = con.prepareStatement(MyQuery);
                //ResultSet res =  pres.executeUpdate();
                pres.setString(1, txtpid.getText());
                pres.setString(2, txtpname.getText());
                pres.setString(3, txtp.getText());
                pres.setString(4, comboptype.getSelectedItem().toString());
                pres.execute();
                JOptionPane.showMessageDialog(this, "Product is Saved");
                
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(this, "Error");
                    JOptionPane.showMessageDialog(this,ex );

                }
            } else {
                JOptionPane.showMessageDialog(this, "Fill the Relevent Fields");
            }
            
            
            
            fillTable();
            //4...producttablevalues();
            
        }catch(SQLException ex){
            Logger.getLogger(ProductMaintance.class.getName()).log(Level.SEVERE, null,ex);

        }

    }//GEN-LAST:event_btnsaveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clearfiels();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btncanselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncanselActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncanselActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        if (!txtpid.getText().isEmpty() || !txtpname.getText().isEmpty() || !txtp.getText().isEmpty()){
            try{
            Connection con = Connections.getConnection();
            String MyQuery = "UPDATE proudcts SET ProductID =?,ProductName=?,Price=?,Category=? WHERE ProductID=?";
            PreparedStatement pres = con.prepareStatement(MyQuery);
            pres.setString(1, txtpid.getText());
            pres.setString(2, txtpname.getText());
            pres.setString(3, txtp.getText());
            pres.setString(4, comboptype.getSelectedItem().toString());
            pres.setString(5, txtpid.getText());
            pres.execute();
            JOptionPane.showMessageDialog(this, "Product Recode is Updated");

        } catch (Exception ex) {
            ///Logger.getLogger(Maintance.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something Went Wrong..!");
            JOptionPane.showMessageDialog(this,ex );
        }
        } else {
            JOptionPane.showMessageDialog(this, "Fill the Relevent Fields");
        }
        
        
        try {
            fillTable();
            /*DefaultTableModel tblModel = (DefaultTableModel) producttable.getModel();
            if(producttable.getSelectedRowCount()==1){
            tblModel.removeRow(producttable.getSelectedRow());
            }else{
            if(producttable.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"Table is Empty" );
            }else{
            JOptionPane.showMessageDialog(this,"Please select a single row foe delete." );
            }
            }*/
        } catch (SQLException ex) {
            Logger.getLogger(ProductMaintance.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        // TODO add your handling code here:
        if (!txtpid.getText().isEmpty()|| !txtpname.getText().isEmpty() || !txtp.getText().isEmpty()){
            try{
                Connection con = Connections.getConnection();
                String MyQuery = "DELETE FROM proudcts WHERE ProductID =?";
                PreparedStatement pres = con.prepareStatement(MyQuery);
                pres.setString(1, txtpid.getText());
                pres.execute();
                JOptionPane.showMessageDialog(this, "Product Recode is Deleted");

            } catch (Exception ex) {
                ///Logger.getLogger(Maintance.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Something Went Wrong..!");
            }
                try {
                    fillTable();
                } catch (SQLException ex) {
                    Logger.getLogger(ProductMaintance.class.getName()).log(Level.SEVERE, null, ex);
                }
        } else {
            JOptionPane.showMessageDialog(this, "Fill the Relevent Fields");
        }
        

    }//GEN-LAST:event_btnremoveActionPerformed

    private void btnclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclrActionPerformed
        try {
            // TODO add your handling code here:
            txtpidsrch.setText(null);
            fillTable();
        } catch (SQLException ex) {
            Logger.getLogger(ProductMaintance.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnclrActionPerformed

    private void producttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_producttableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) producttable.getModel();
        int selectedRowIndex = producttable.getSelectedRow();
        
        txtpid.setText(tblModel.getValueAt(selectedRowIndex,0).toString());
        txtpname.setText(tblModel.getValueAt(selectedRowIndex,1).toString());
        txtp.setText(tblModel.getValueAt(selectedRowIndex,2).toString());
        //comboptype.setModel(tblModel.getValueAt(selectedRowIndex,0).toString());
        String Category = tblModel.getValueAt(selectedRowIndex,3).toString();
        comboptype.setSelectedItem(Category);
        txtpidsrch.setText(tblModel.getValueAt(selectedRowIndex,0).toString());
    }//GEN-LAST:event_producttableMouseClicked

    
     public void clearfiels(){
        
        txtpid.setText(null);
        txtpname.setText(null);
        txtp.setText(null);
        comboptype.setSelectedIndex(0);
        
    }
     
     
     /*private void updatetable(){
        try{
           Connection con = Connections.getConnection();
            String MyQuery = "SELECT *FROM proudcts";
            PreparedStatement pres = con.prepareStatement(MyQuery);
            pres.execute();  
            producttable.setModel(DbUtils.resultSetToTableModel(rs));
               
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this,ex );
        }
            
        
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductMaintance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductMaintance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductMaintance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductMaintance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProductMaintance().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ProductMaintance.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncansel;
    private javax.swing.JButton btnclr;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsrch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> comboptype;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable producttable;
    private javax.swing.JTextField txtp;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtpidsrch;
    private javax.swing.JTextField txtpname;
    // End of variables declaration//GEN-END:variables

    
}
